version = 1

[qwen3.8-27b-SHORT-BASE]
; Ruta de ejemplo: sustituye CAMBIA_ESTA_RUTA por tu GGUF real.
m = E:\models\Qwen\CAMBIA_ESTA_RUTA-Qwen3.8-27B.gguf
jinja = true
fit = on
frequency-penalty = 0
min-p = 0
batch-size = 128
ctx-size = 4096
parallel = 1
presence-penalty = 0
repeat-penalty = 1
temp = 0
top-k = 20
top-p = 0.95
reasoning = off

spec-type = none
